In [72]:
%run CFBmodel/import_modules.ipynb
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = 'MyjBpIrnMbCmsxXJD6zmiOCWqjB3p+7Icq5PRSrN82IXeOppkoEWybx1SmRryxT+'
configuration.api_key_prefix['Authorization']='Bearer'
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
# game_id=game_id  season_type=season_type, team=team, home=home, away=away, conference=conference)

In [70]:
con=sqlite3.connect('CFBModel/collegeFootball.db')
cursor_obj= con.cursor()
games = pd.read_sql("""SELECT * FROM Games23""", con)
for games in games.id:

SyntaxError: incomplete input (1118348014.py, line 4)

In [ ]:
games

In [120]:
import pandas as pd

def parse_data(game_id):
    try:
        data = api_instance.get_advanced_box_score(game_id=game_id)
        
        # Check if data is None
        if data is None:
            print(f"Warning: No data returned for game ID {game_id}.")
            return pd.DataFrame(), pd.DataFrame()  # Return empty DataFrames

        combined_players = []
        combined_teams = []

        # Parse players
        for player in data.players.ppa:
            player_info = {
                'game_id': game_id,  # Add game_id to player info
                'player': player.player,
                'position': player.position,
                'team': player.team,
                'average_passing': player.average.passing,
                'average_rushing': player.average.rushing,
                'cumulative_passing': player.cumulative.passing,
                'cumulative_rushing': player.cumulative.rushing,
                'total_average': player.average.total,
                'total_cumulative': player.cumulative.total
            }
            combined_players.append(player_info)

        # Parse teams
        for team in data.teams.cumulative_ppa:
            team_info = {
                'game_id': game_id,  # Add game_id to team info
                'team': team.team,
                'plays': team.plays,
                'overall_quarter1': team.overall.quarter1,
                'overall_quarter2': team.overall.quarter2,
                'overall_quarter3': team.overall.quarter3,
                'overall_quarter4': team.overall.quarter4,
                'overall_total': team.overall.total,
                'passing_quarter1': team.passing.quarter1,
                'passing_quarter2': team.passing.quarter2,
                'passing_quarter3': team.passing.quarter3,
                'passing_quarter4': team.passing.quarter4,
                'passing_total': team.passing.total,
                'rushing_quarter1': team.rushing.quarter1,
                'rushing_quarter2': team.rushing.quarter2,
                'rushing_quarter3': team.rushing.quarter3,
                'rushing_quarter4': team.rushing.quarter4,
                'rushing_total': team.rushing.total
            }
            combined_teams.append(team_info)

        # Create DataFrames from the lists of dictionaries
        players_df = pd.DataFrame(combined_players)
        teams_df = pd.DataFrame(combined_teams)

        return players_df, teams_df

    except Exception as e:
        print(f"Error processing game ID {game_id}: {e}")
        return pd.DataFrame(), pd.DataFrame()  # Return empty DataFrames in case of error

def get_box_scores(game_ids):
    results = [parse_data(game_id) for game_id in game_ids]

    # Split the results into players and teams DataFrames
    players_data = [result[0] for result in results]
    teams_data = [result[1] for result in results]

    # Concatenate all DataFrames
    combined_players_df = pd.concat(players_data, ignore_index=True) if players_data else pd.DataFrame()
    combined_teams_df = pd.concat(teams_data, ignore_index=True) if teams_data else pd.DataFrame()

    return combined_players_df, combined_teams_df

combined_players_df_2, combined_teams_df = get_box_scores(games.id.tail(2))

In [121]:
combined_players_df_2023

,game_id,player,position,team,average_passing,average_rushing,cumulative_passing,cumulative_rushing,total_average,total_cumulative
0,401539480,J.J. McCarthy,QB,Michigan,0.074,0.081,2.4,0.2,0.075,2.5
1,401539480,Deacon Hill,QB,Iowa,-0.055,-1.107,-1.2,-4.4,-0.217,-5.6
2,401539480,Blake Corum,RB,Michigan,0.105,-0.120,0.2,-1.4,-0.088,-1.2
3,401539480,Leshon Williams,RB,Iowa,0.000,-0.161,0.0,-1.4,-0.161,-1.4
4,401539480,Kaleb Brown,WR,Iowa,0.371,0.033,2.2,0.1,0.287,2.3
5,401539480,Cornelius Johnson,WR,Michigan,0.695,-1.096,5.6,-1.1,0.496,4.5
6,401539480,Donovan Edwards,RB,Michigan,0.025,0.216,0.1,0.9,0.121,1.0
7,401539480,Kaleb Johnson,RB,Iowa,0.000,-0.329,0.0,-2.0,-0.329,-2.0
8,401539480,Addison Ostrenga,TE,Iowa,0.128,0.000,0.8,0.0,0.128,0.8
9,401539480,Colston Loveland,TE,Michigan,-0.126,0.000,-0.9,0.0,-0.126,-0.9
10,401539480,Nico Ragaini,WR,Iowa,-0.103,0.000,-0.4,0.0,-0.103,-0.4
11,401539480,Kalel Mullings,RB,Michigan,0.000,0.078,0.0,0.2,0.078,0.2
12,401539480,Roman Wilson,WR,Michigan,0.460,0.000,1.4,0.0,0.460,1.4
13,401539480,Jaziun Patterson,RB,Iowa,0.000,-2.107,0.0,-4.2,-2.107,-4.2
14,401539480,A.J. Barner,TE,Michigan,0.842,0.000,1.7,0.0,0.842,1.7
15,401539480,Hayden Large,FB,Iowa,-0.644,0.000,-0.6,0.0,-0.644,-0.6
16,401539480,Peyton O'Leary,WR,Michigan,0.034,0.000,0.0,0.0,0.034,0.0
17,401539480,Alex Orji,QB,Michigan,0.000,0.110,0.0,0.1,0.110,0.1
18,401520445,Tai Lavatai,QB,Navy,0.518,0.043,15.0,0.6,0.356,15.7
19,401520445,Bryson Daily,QB,Army,0.357,-0.130,5.0,-3.2,0.045,1.8
20,401520445,Kanye Udoh,RB,Army,0.000,0.149,0.0,1.8,0.149,1.8
21,401520445,Alex Tecza,FB,Navy,0.042,-0.150,0.1,-1.3,-0.115,-1.3
22,401520445,Jayden Umbarger,WR,Navy,1.562,0.000,12.5,0.0,1.562,12.5
23,401520445,Casey Reynolds,WR,Army,0.095,0.000,0.7,0.0,0.095,0.7
24,401520445,Xavier Arline,QB,Navy,-0.730,-0.224,-1.5,-1.1,-0.368,-2.6
25,401520445,Eli Heidenreich,RB,Navy,0.094,0.000,0.6,0.0,0.094,0.6
26,401520445,Brandon Chatman,RB,Navy,0.309,1.139,1.5,1.1,0.447,2.7
27,401520445,Jakobi Buchanan,RB,Army,0.000,-0.340,0.0,-1.4,-0.340,-1.4
28,401520445,Ay'Juan Marshall,WR,Army,-0.041,0.307,-0.1,0.6,0.133,0.5
29,401520445,Noah Short,RB,Army,-1.211,0.000,-2.4,0.0,-1.211,-2.4
30,401520445,Tobi Olawole,WR,Army,1.024,0.000,1.0,0.0,1.024,1.0
31,401520445,Tyrell Robinson,RB,Army,0.000,0.102,0.0,0.1,0.102,0.1
32,401520445,Riley Tyson,RB,Army,6.881,0.000,6.9,0.0,6.881,6.9
33,401520445,Cody Howard,TE,Navy,0.186,0.000,0.2,0.0,0.186,0.2
34,401520445,Nathan Kent,WR,Navy,1.314,0.000,1.3,0.0,1.314,1.3
35,401520445,Daba Fofana,FB,Navy,0.000,-0.036,0.0,0.0,-0.036,0.0

In [114]:
players_df, teams_df= parse_data(game_id=401525434)

In [115]:
def get_box_scores(game_ids):
    # Fetch and parse data for all game IDs using a list comprehension
    results = [parse_data(game_id) for game_id in game_ids]

    # Split the results into players and teams DataFrames
    players_data = [result[0] for result in results]
    teams_data = [result[1] for result in results]

    # Concatenate all DataFrames
    combined_players_df = pd.concat(players_data, ignore_index=True)
    combined_teams_df = pd.concat(teams_data, ignore_index=True)

    return combined_players_df, combined_teams_df

# Example usa# Replace with your actual list of game IDs
combined_players_df, combined_teams_df = get_box_scores(games.id)

# Display the DataFrames
print("Combined Players DataFrame:\n", combined_players_df)
print("Combined Teams DataFrame:\n", combined_teams_df)

AttributeError: 'NoneType' object has no attribute 'ppa'

In [96]:
parse_season_data(games.id)

Empty DataFrame
Columns: [game_id]
Index: []

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [52]:
import pandas as pd

def get_coaches(start):
    combined_data = []  # List to collect game data

    for j in range(start, 2025):  # Loop through weeks
        coach_data = api_instance.get_coaches(year=j)

        for coach in coach_data:
            # Compile all data into a single dictionary for each line
            game_info = {
                    'first_name': coach.first_name,
                    'hire_date': coach.hire_date,
                    'season_type': coach.last_name,
                    'year': j,
                     'games': coach.seasons[0].games,
                   'losses': coach.seasons[0].losses,
                   'postseason_rank': coach.seasons[0].postseason_rank,
                   'preseason_rank': coach.seasons[0].preseason_rank,
                   'school': coach.seasons[0].school,
                   'sp_defense':coach.seasons[0].sp_defense,
                   'sp_offense': coach.seasons[0].sp_offense,
                   'sp_overall': coach.seasons[0].sp_overall
                }
            combined_data.append(game_info)
            i=0
            for season in coach.seasons:
                coach_info = {
                     'games{}'.format(i): coach.seasons[0].games,
                   'losses{}'.format(i): coach.seasons[0].losses,
                   'postseason_rank{}'.format(i): coach.seasons[0].postseason_rank,
                   'preseason_rank{}'.format(i): coach.seasons[0].preseason_rank,
                   'school{}'.format(i): coach.seasons[0].school,
                   'sp_defense{}'.format(i):coach.seasons[0].sp_defense,
                   'sp_offense{}'.format(i): coach.seasons[0].sp_offense,
                   'sp_overall{}'.format(i): coach.seasons[0].sp_overall
                }
                i=i+1
                combined_data.append(coach_info)  # Append the dictionary to the list

    # Create a DataFrame from the list of dictionaries
    df = pd.DataFrame(combined_data)
    return df

In [55]:
coachHist=get_coaches(start=1980)

In [60]:
coachHist.sp_offense0.value_counts()

sp_offense0
32.0    57
34.2    52
27.8    52
24.5    48
29.9    47
        ..
43.7     1
46.4     1
49.6     1
13.9     1
12.4     1
Name: count, Length: 410, dtype: int64

In [61]:
con=sqlite3.connect('CFBModel/collegeFootball.db')
cursor_obj= con.cursor()
cursor_obj.execute("DROP TABLE IF EXISTS coachHist")
coachHist.to_sql(name='coachHist',con=con)

10796

In [62]:
con.commit()
con.close()